### ISSUE TITLE
Call dibs on a TODO list item

### ISSUE THREAD

**Issue by ohiofi** [BradleyCodeU/HomeRunDerby2023#1]
Copy/paste the TODO list item that you are calling dibs on

!!!DON'T FORGET TO ADD JAVADOC COMMENTS!!!

# TO DO LIST:

### HomeRunDerby object

- [x]  Constructor with 2 args: Pitcher, Batter
- [x]  void setPitchNumber(int pitchNumber)
- [x]  void nextPitch() // mutator method with no args, increments pitchNumber and mutates the batter and pitcher to move on to the next pitch
- [x]  String getResults() // accessor that says if the pitch was good/bad, if the swing was good/bad, and the resulting play. See the table below for how to get the resulting play...

|   |GOOD PITCH|BAD PITCH|
|---|---|---|
|GOOD SWING| Hit | Home Run |
|BAD SWING| Strike | Foul Ball |

### Batter object
- [x]  create String getName()
- [x]  update String getSwing() so that it does NOT mutate the object
- [ ]  create boolean isGoodSwing() // returns True/False using the isVowel method with name and pitchNumber as args
- [x]  create void setPitchNumber(int pitchNumber)
- [x]  create void nextPitch() // mutator method with no args, increments pitchNumber
- [x]  isVowel

### Pitcher object
- [x]  create String getName()
- [x]  update String getPitch() so that it does NOT mutate the object
- [ ]  create boolean isGoodPitch() // returns True/False using the isVowel method with name and pitchNumber as args
- [ ]  create void setPitchNumber(int pitchNumber)
- [ ]  create void nextPitch() // mutator method with no args, increments pitchNumber
- [x]  isVowel

**Comment by XiLx** [comment]
i call dibs on HomeRunDerby constructor

**Comment by Conlan-116** [comment]
I call dibs on void nextPitch() **In the HomeRunDerby object**

**Comment by ConnerW7** [comment]
I call dibs on  String getResults()

**Comment by CraigDixon123** [comment]
I call dibs on getName() for the Batter object

**Comment by LanceTho** [comment]
I call dibs on String getName() for the Pitcher object

**Comment by Itsaa4** [comment]
I call dibs on HomeRunDerby void setPitchNumber(int pitchNumber)

**Comment by CampbellToeOfficial** [comment]
I call dibs on Batter create void setPitchNumber(int pitchNumber)

**Comment by owen60** [comment]
I call dibs on  update String getSwing() so that it does NOT mutate the object

**Comment by LanceM98** [comment]
update String getPitch() so that it does NOT mutate the object

**Comment by kadenw07** [comment]
I call dibs on batter nextPitch

**Comment by LukeIsTheGoat** [comment]
i call dibs on  create boolean isGoodSwing() // returns True/False using the isVowel method with name and pitchNumber as args
